export const countryCodes = [
  {
    name: "Afghanistan",
    dial_code: "+93",
    code: "AF",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Albania",
    dial_code: "+355",
    code: "AL",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Algeria",
    dial_code: "+213",
    code: "DZ",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "American Samoa",
    dial_code: "+1-684",
    code: "AS",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Andorra",
    dial_code: "+376",
    code: "AD",
    minLength: 6,
    maxLength: 9,
  },
  { name: "Angola", dial_code: "+244", code: "AO", minLength: 9, maxLength: 9 },
  {
    name: "Argentina",
    dial_code: "+54",
    code: "AR",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Armenia",
    dial_code: "+374",
    code: "AM",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Australia",
    dial_code: "+61",
    code: "AU",
    minLength: 9,
    maxLength: 10,
  },
  {
    name: "Austria",
    dial_code: "+43",
    code: "AT",
    minLength: 10,
    maxLength: 13,
  },
  {
    name: "Azerbaijan",
    dial_code: "+994",
    code: "AZ",
    minLength: 9,
    maxLength: 9,
  },
  {
    name: "Bahamas",
    dial_code: "+1-242",
    code: "BS",
    minLength: 7,
    maxLength: 7,
  },
  {
    name: "Bahrain",
    dial_code: "+973",
    code: "BH",
    minLength: 8,
    maxLength: 8,
  },
  {
    name: "Bangladesh",
    dial_code: "+880",
    code: "BD",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Barbados",
    dial_code: "+1-246",
    code: "BB",
    minLength: 7,
    maxLength: 7,
  },
  { name: "Belgium", dial_code: "+32", code: "BE", minLength: 8, maxLength: 9 },
  {
    name: "Brazil",
    dial_code: "+55",
    code: "BR",
    minLength: 10,
    maxLength: 11,
  },
  { name: "Canada", dial_code: "+1", code: "CA", minLength: 10, maxLength: 10 },
  { name: "China", dial_code: "+86", code: "CN", minLength: 11, maxLength: 11 },
  { name: "France", dial_code: "+33", code: "FR", minLength: 9, maxLength: 9 },
  {
    name: "Germany",
    dial_code: "+49",
    code: "DE",
    minLength: 10,
    maxLength: 15,
  },
  { name: "India", dial_code: "+91", code: "IN", minLength: 10, maxLength: 10 },
  { name: "Italy", dial_code: "+39", code: "IT", minLength: 9, maxLength: 10 },
  { name: "Japan", dial_code: "+81", code: "JP", minLength: 10, maxLength: 11 },
  {
    name: "Mexico",
    dial_code: "+52",
    code: "MX",
    minLength: 10,
    maxLength: 10,
  },
  { name: "Russia", dial_code: "+7", code: "RU", minLength: 10, maxLength: 10 },
  {
    name: "South Korea",
    dial_code: "+82",
    code: "KR",
    minLength: 9,
    maxLength: 11,
  },
  { name: "Spain", dial_code: "+34", code: "ES", minLength: 9, maxLength: 9 },
  {
    name: "United Kingdom",
    dial_code: "+44",
    code: "GB",
    minLength: 10,
    maxLength: 11,
  },
  {
    name: "United States",
    dial_code: "+1",
    code: "US",
    minLength: 10,
    maxLength: 10,
  },
  {
    name: "Vietnam",
    dial_code: "+84",
    code: "VN",
    minLength: 9,
    maxLength: 11,
  },
];
