export const SUPPORTED_COUNTRIES = [
  { code: "AU", name: "Australia", currency: "aud" },
  { code: "AT", name: "Austria", currency: "eur" },
  { code: "BE", name: "Belgium", currency: "eur" },
  { code: "BG", name: "Bulgaria", currency: "bgn" },
  { code: "BR", name: "Brazil", currency: "brl" },
  { code: "CA", name: "Canada", currency: "cad" },
  { code: "HR", name: "Croatia", currency: "eur" },
  { code: "CY", name: "Cyprus", currency: "eur" },
  { code: "CZ", name: "Czech Republic", currency: "czk" },
  { code: "DK", name: "Denmark", currency: "dkk" },
  { code: "EE", name: "Estonia", currency: "eur" },
  { code: "FI", name: "Finland", currency: "eur" },
  { code: "FR", name: "France", currency: "eur" },
  { code: "DE", name: "Germany", currency: "eur" },
  { code: "GI", name: "Gibraltar", currency: "gbp" },
  { code: "GR", name: "Greece", currency: "eur" },
  { code: "HK", name: "Hong Kong", currency: "hkd" },
  { code: "HU", name: "Hungary", currency: "huf" },
  { code: "IE", name: "Ireland", currency: "eur" },
  { code: "IL", name: "Israel", currency: "ils" },
  { code: "IT", name: "Italy", currency: "eur" },
  { code: "JP", name: "Japan", currency: "jpy" },
  { code: "LT", name: "Lithuania", currency: "eur" },
  { code: "LU", name: "Luxembourg", currency: "eur" },
  { code: "LV", name: "Latvia", currency: "eur" },
  { code: "MT", name: "Malta", currency: "eur" },
  { code: "MX", name: "Mexico", currency: "mxn" },
  { code: "NL", name: "Netherlands", currency: "eur" },
  { code: "NZ", name: "New Zealand", currency: "nzd" },
  { code: "NO", name: "Norway", currency: "nok" },
  { code: "PL", name: "Poland", currency: "pln" },
  { code: "PT", name: "Portugal", currency: "eur" },
  { code: "RO", name: "Romania", currency: "ron" },
  { code: "SG", name: "Singapore", currency: "sgd" },
  { code: "SK", name: "Slovakia", currency: "eur" },
  { code: "SI", name: "Slovenia", currency: "eur" },
  { code: "ES", name: "Spain", currency: "eur" },
  { code: "SE", name: "Sweden", currency: "sek" },
  { code: "CH", name: "Switzerland", currency: "chf" },
  { code: "TW", name: "Taiwan", currency: "twd" },
  { code: "TH", name: "Thailand", currency: "thb" },
  { code: "AE", name: "United Arab Emirates", currency: "aed" },
  { code: "GB", name: "United Kingdom", currency: "gbp" },
  { code: "US", name: "United States", currency: "usd" },
  { code: "UY", name: "Uruguay", currency: "uyu" },
];
